use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Moya_ErrorObjectMapper_Example' do
  pod 'Moya-ErrorObjectMapper/RxSwift', :path => '../'

  target 'Moya_ErrorObjectMapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
