use_frameworks!

target 'Moya-ErrorObjectMapper_Example' do
  pod 'Moya-ErrorObjectMapper', :path => '../'

  target 'Moya-ErrorObjectMapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
